### ISSUE TITLE
AttributeError: 'SplattingModel' object has no attribute 'gauss_params'

### ISSUE THREAD

**Issue by MrDieAlot** [grasp-lyrl/NeRFtoGSandBack#1]
Getting the following error when trying out the ns-splatting command.

Traceback (most recent call last):
  File "C:\Users\s_m_d\miniforge3\envs\nerfstudio\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\s_m_d\miniforge3\envs\nerfstudio\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\s_m_d\miniforge3\envs\nerfstudio\Scripts\ns-train.exe\__main__.py", line 7, in <module>
  File "C:\nerfstudio\nerfstudio\scripts\train.py", line 262, in entrypoint
    main(
  File "C:\nerfstudio\nerfstudio\scripts\train.py", line 247, in main
    launch(
  File "C:\nerfstudio\nerfstudio\scripts\train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "C:\nerfstudio\nerfstudio\scripts\train.py", line 99, in train_loop
    trainer.setup()
  File "C:\nerfstudio\nerfstudio\engine\trainer.py", line 160, in setup
    self.optimizers = self.setup_optimizers()
  File "C:\nerfstudio\nerfstudio\engine\trainer.py", line 225, in setup_optimizers
    param_groups = self.pipeline.get_param_groups()
  File "C:\nerfstudio\nerfstudio\pipelines\base_pipeline.py", line 441, in get_param_groups
    model_params = self.model.get_param_groups()
  File "C:\nerfstudio\nerfstudio\models\splatfacto.py", line 633, in get_param_groups
    gps = self.get_gaussian_param_groups()
  File "C:\nerfstudio\nerfstudio\models\splatfacto.py", line 622, in get_gaussian_param_groups
    return {
  File "C:\nerfstudio\nerfstudio\models\splatfacto.py", line 623, in <dictcomp>
    name: [self.gauss_params[name]]
  File "C:\Users\s_m_d\miniforge3\envs\nerfstudio\lib\site-packages\torch\nn\modules\module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'SplattingModel' object has no attribute 'gauss_params'

**Comment by Siming-He** [comment]
Hi, thank you for reporting the error! 

Could you tell me in more details about the command you are running? I update the code yesterday so that "splatting" method is called "nerfgs" now (to align with the naming in the paper). 

Could you also mention your Python, nerfstudio, gsplat, and Torch version?

**Comment by MrDieAlot** [comment]
Hi! Got the same error with the new version, having re-installed everything. Had to install some additional dependencies that I've seen you've now added.

This is the command I'm running, and also get a warning straight after 

(nerfstudio) B:\>ns-train nerfgs --data Nerfs\NerfToGs\Wissahickon --max-num-iterations 1 --pipeline.model.ply-file-path Nerfs\nerfgs\nerfgs.ply nerfstudio-data --eval-mode filename
C:\Users\s_m_d\miniforge3\envs\nerfstudio\lib\site-packages\tyro\_fields.py:343: UserWarning: The field ply_file_path is annotated with type <class 'str'>, but the default value None has type <class 'NoneType'>. We'll try to handle this gracefully, but it may cause unexpected behavior.
  warnings.warn(

Am running python 3.10 through miniforge, Nerfstudio version 1.10 in a dedicated environment, latest dev version, Torch 2.1.2. Not sure about gsplat, that the same as splatfacto?

**Comment by Siming-He** [comment]
> Getting the following error when trying out the ns-splatting command.
> 
> Traceback (most recent call last): File "C:\Users\s_m_d\miniforge3\envs\nerfstudio\lib\runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "C:\Users\s_m_d\miniforge3\envs\nerfstudio\lib\runpy.py", line 86, in _run_code exec(code, run_globals) File "C:\Users\s_m_d\miniforge3\envs\nerfstudio\Scripts\ns-train.exe__main__.py", line 7, in File "C:\nerfstudio\nerfstudio\scripts\train.py", line 262, in entrypoint main( File "C:\nerfstudio\nerfstudio\scripts\train.py", line 247, in main launch( File "C:\nerfstudio\nerfstudio\scripts\train.py", line 189, in launch main_func(local_rank=0, world_size=world_size, config=config) File "C:\nerfstudio\nerfstudio\scripts\train.py", line 99, in train_loop trainer.setup() File "C:\nerfstudio\nerfstudio\engine\trainer.py", line 160, in setup self.optimizers = self.setup_optimizers() File "C:\nerfstudio\nerfstudio\engine\trainer.py", line 225, in setup_optimizers param_groups = self.pipeline.get_param_groups() File "C:\nerfstudio\nerfstudio\pipelines\base_pipeline.py", line 441, in get_param_groups model_params = self.model.get_param_groups() File "C:\nerfstudio\nerfstudio\models\splatfacto.py", line 633, in get_param_groups gps = self.get_gaussian_param_groups() File "C:\nerfstudio\nerfstudio\models\splatfacto.py", line 622, in get_gaussian_param_groups return { File "C:\nerfstudio\nerfstudio\models\splatfacto.py", line 623, in name: [self.gauss_params[name]] File "C:\Users\s_m_d\miniforge3\envs\nerfstudio\lib\site-packages\torch\nn\modules\module.py", line 1695, in **getattr** raise AttributeError(f"'{type(self).**name**}' object has no attribute '{name}'") AttributeError: 'SplattingModel' object has no attribute 'gauss_params'

I just fixed this error. Could you try again by running
`ns-train nerfgs --data DATA-PATH --max-num-iterations 1 --pipeline.model.ply-file-path exports/nerfgs/nerfgs.ply nerfstudio-data --eval-mode filename`

I was using a very old version of nerfstudio. So I have to update the nerfgsModel for the newer nerfstudio versions.

**Comment by MrDieAlot** [comment]
The training works now, but the result from running nerfgs in the viser, as well as the output ply looks odd. Attaching file of it.

![Screenshot 2024-05-20 120517](https://github.com/grasp-lyrl/NeRFtoGSandBack/assets/35977193/9acaef52-5fa0-4133-9d27-8143a53e9f0e)

Also getting this warning:
C:\Users\s_m_d\miniforge3\envs\nerfstudio\lib\site-packages\torch\optim\lr_scheduler.py:136: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "

And still getting this warning, don't know if it's relevant: 
C:\Users\s_m_d\miniforge3\envs\nerfstudio\lib\site-packages\tyro\_fields.py:343: UserWarning: The field ply_file_path is annotated with type <class 'str'>, but the default value None has type <class 'NoneType'>. We'll try to handle this gracefully, but it may cause unexpected behavior.
  warnings.warn(

**Comment by Siming-He** [comment]
> The training works now, but the result from running nerfgs in the viser, as well as the output ply looks odd. Attaching file of it.
> 
> ![Screenshot 2024-05-20 120517](https://private-user-images.githubusercontent.com/35977193/332025112-9acaef52-5fa0-4133-9d27-8143a53e9f0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NTE5MDgsIm5iZiI6MTcxNjc1MTYwOCwicGF0aCI6Ii8zNTk3NzE5My8zMzIwMjUxMTItOWFjYWVmNTItNWZhMC00MTMzLTlkMjctODE0M2E1M2U5ZjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDE5MjY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMTAxYzc5MmFhODgxYjU2MTBkMzVjNjFkZWFlZmRlNDU5ODYxOWMwMDY2NzJhZDEyMTU5NDM3YWZlNjlmMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8PmQBEIs6ye79KoJ1kXL325ywBbjGwuJtSpTmxmfgts)
> 
> Also getting this warning: C:\Users\s_m_d\miniforge3\envs\nerfstudio\lib\site-packages\torch\optim\lr_scheduler.py:136: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`. Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
> 
> And still getting this warning, don't know if it's relevant: C:\Users\s_m_d\miniforge3\envs\nerfstudio\lib\site-packages\tyro_fields.py:343: UserWarning: The field ply_file_path is annotated with type <class 'str'>, but the default value None has type <class 'NoneType'>. We'll try to handle this gracefully, but it may cause unexpected behavior. warnings.warn(

Hi, does it work when you use older version of nerfstudio?

**Comment by MrDieAlot** [comment]
Yes, I managed to get it to work that way!
